import React from 'react';
import { siteConfig } from '../config/siteConfig';

const Disclaimer: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12 text-gray-800 leading-relaxed">
      <h1 className="text-3xl font-bold mb-8">Legal Disclaimer</h1>
      
      <section className="mb-8">
        <p className="mb-4">
          ScrappyChef (operating as a {siteConfig.legalStructure} by {siteConfig.legalName}) 
          provides this application and its content for informational and inspirational purposes only.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4">1. Food Safety & AI Recipes</h2>
        <p className="mb-4">
          🤖 AI-generated recipes are generated by large language models and have not been tested for 
          human consumption by professional chefs or nutritionists. ScrappyChef cannot guarantee the accuracy, 
          safety, or quality of these recipes.
        </p>
        <p className="mb-4 font-bold text-red-700">
          Always inspect your ingredients for freshness, spoilage, and signs of decay before use. 
          Use your best judgment when interpreting instructions.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4">2. Allergens & Health</h2>
        <p className="mb-4">
          Users are solely responsible for identifying and managing food allergens. 
          The matching engine and AI generator do not account for personal medical conditions, 
          allergies, or dietary restrictions unless explicitly managed by the user.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4">3. No Warranty ("As-Is")</h2>
        <p className="mb-4 italic">
          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
          INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
          PURPOSE AND NONINFRINGEMENT.
        </p>
        <p className="mb-4">
          In no event shall the authors or copyright holders be liable for any claim, damages 
          or other liability, whether in an action of contract, tort or otherwise, arising from, 
          out of or in connection with the software or the use or other dealings in the software.
        </p>
      </section>

      <section className="mb-8 border-t pt-8">
        <p className="text-sm text-gray-500">
          Last updated: June 2026<br />
          Contact: {siteConfig.supportEmail}
        </p>
      </section>
    </div>
  );
};

export default Disclaimer;
